# Generated by Django 4.0.4 on 2022-07-03 15:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.CharField(max_length=3)),
                ('income_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('sclass', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=25)),
                ('fees', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='eccc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eccc_course', models.CharField(max_length=25)),
                ('no_of_seats', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('notification_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=25)),
                ('recieve', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=25)),
                ('dept', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student'), (4, 'Parent')], default=1, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subject_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.classes')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='subject_handled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.staff')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sclass', models.CharField(max_length=25)),
                ('section', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('DOB', models.DateField(default='1998-01-01')),
                ('academic_advisor', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('achievements', models.CharField(max_length=100)),
                ('scholarship', models.CharField(max_length=50)),
                ('fees', models.CharField(max_length=10)),
                ('midday_meal', models.CharField(max_length=20)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=20)),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.stud')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('leave_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=100)),
                ('leave_date', models.DateField()),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.stud')),
            ],
        ),
        migrations.CreateModel(
            name='hod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=15)),
                ('class_held', models.CharField(max_length=3)),
                ('class_attended', models.CharField(max_length=3)),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.stud')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.subjects')),
            ],
        ),
    ]
